export const dynamic = "force-dynamic";

import { ArrowDown, ArrowUp, Trash2 } from "lucide-react";
import { prisma } from "@/lib/db";
import { createClassAction, deleteOrHideClassAction, moveClassAction, updateClassAction } from "@/lib/admin-actions";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

export default async function ClassesPage() {
  const classes = await prisma.imageClass.findMany({ orderBy: { sortOrder: "asc" }, include: { _count: { select: { annotations: true } } } });
  return <main className="space-y-6 p-6"><div><h1 className="text-2xl font-semibold tracking-tight">Classes</h1><p className="text-sm text-muted-foreground">Manage labels and display order.</p></div><form action={createClassAction} className="flex max-w-2xl gap-2"><Input name="name" placeholder="Class name" required /><Input name="colorHex" placeholder="#0f172a" className="w-36" /><Button type="submit">Add</Button></form><div className="rounded-lg border"><Table><TableHeader><TableRow><TableHead>Order</TableHead><TableHead>Name</TableHead><TableHead>Color</TableHead><TableHead>Status</TableHead><TableHead>Votes</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{classes.map((item) => <TableRow key={item.id}><TableCell className="w-28"><div className="flex gap-1"><form action={moveClassAction}><input type="hidden" name="id" value={item.id} /><input type="hidden" name="direction" value="up" /><Button size="icon" variant="ghost"><ArrowUp className="size-4" /></Button></form><form action={moveClassAction}><input type="hidden" name="id" value={item.id} /><input type="hidden" name="direction" value="down" /><Button size="icon" variant="ghost"><ArrowDown className="size-4" /></Button></form></div></TableCell><TableCell><form id={`class-${item.id}`} action={updateClassAction} className="flex gap-2"><input type="hidden" name="id" value={item.id} /><Input name="name" defaultValue={item.name} /></form></TableCell><TableCell><Input form={`class-${item.id}`} name="colorHex" defaultValue={item.colorHex ?? ""} className="w-32" /></TableCell><TableCell><label className="flex items-center gap-2 text-sm"><input form={`class-${item.id}`} type="checkbox" name="isActive" defaultChecked={item.isActive} />{item.isActive ? "Active" : "Hidden"}</label></TableCell><TableCell>{item._count.annotations}</TableCell><TableCell className="text-right"><div className="flex justify-end gap-2"><Button form={`class-${item.id}`} type="submit" variant="outline">Save</Button><form action={deleteOrHideClassAction}><input type="hidden" name="id" value={item.id} /><Button size="icon" variant="ghost" title={item._count.annotations ? "Hide class because votes exist" : "Delete class"}><Trash2 className="size-4" /></Button></form></div></TableCell></TableRow>)}</TableBody></Table></div></main>;
}

